# Generated by Django 5.1.3 on 2024-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
    ]
